// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function OnBoardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <div className="sm:mx-40 sm:my-5">{children}</div>
}
