// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

import MaxWidthContainer from '@/components/common/max-width-container'
import OnBoardingHeader from '@/components/on-boarding/on-boarding-header'

export default function OnBoardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <OnBoardingHeader />
      <MaxWidthContainer>
        <main className="flex h-full w-full items-center justify-center">
          {children}
        </main>
      </MaxWidthContainer>
    </div>
  )
}
